export const lyrics = [
    "Indonesia Pusaka",
    "Indonesia tanah air beta",
    "Pusaka abadi nan jaya",
    "Indonesia sejak dulu kala",
    "Tetap dipuja-puja bangsa",
    "Disana tempat lahir beta",
    "Dibuai dibesarkan bunda",
    "Tempat berlindung di hari tua",
    "Tempat akhir menutup mata",
    "Sungguh Indah Tanah Air Beta",
    "Tiada Bandingnya di Dunia",
    "Karya Indah Tuhan Maha Kuasa",
    "Bagi Bangsa yang Memujanya",
    "Indonesia Ibu Pertiwi",
    "Kau Kupuja Kau Kukasihi",
    "Tenagaku bahkanpun Jiwaku",
    "Kepadamu rela kuberi",
]
